In [1]:
import pandas as pd
from eodhd import APIClient
import sys
sys.path.insert(0, "../src/")
from Features import technical_features
import talib

In [2]:
obj = technical_features.BuildFeatures('MSFT')

In [3]:
obj.stock.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13 00:00:00-05:00,0.05448535,0.06249798,0.05448535,0.05982669,1031788800,0.00000000,0.00000000
1986-03-14 00:00:00-05:00,0.05982675,0.06303217,0.05982675,0.06196329,308160000,0.00000000,0.00000000
1986-03-17 00:00:00-05:00,0.06196329,0.06356631,0.06196329,0.06303217,133171200,0.00000000,0.00000000
1986-03-18 00:00:00-05:00,0.06303211,0.06356624,0.06089496,0.06142909,67766400,0.00000000,0.00000000
1986-03-19 00:00:00-05:00,0.06142916,0.06196329,0.05982676,0.06036089,47894400,0.00000000,0.00000000

In [4]:
obj.build_technical_features()

In [5]:
obj.technical_features.tail()

,SMA_50,SMA_200,Chaikin_ADI_Line,Chaikin_ADI_Oscillator,ADM_Index,ADM_Index_Rating,Absolute_Price_Oscillator,Aroon,Aroon_Oscillator,Average_True_Range,Average_Price,Bollinger_Band_Upper,Bollinger_Band_Middle,Bollinger_Band_Lower,Beta,Balance_of_Power,Commodity_Channel_Index
Date,,,,,,,,,,,,,,,,,
2025-01-17 00:00:00-05:00,428.51676453,423.98321686,12633056769.02912331,-7538306.92732811,19.79282916,20.40085806,-9.97461251,NaN,NaN,8.36096550,431.44250488,432.99869751,422.55599976,412.11330201,0.68993812,-0.80190167,126.25396435
2025-01-21 00:00:00-05:00,428.87400391,424.03521179,12635517689.79148865,-8952680.43404388,18.71150250,19.94231047,-8.82089507,NaN,NaN,8.14232424,428.80000305,434.50371754,424.81799927,415.13228099,0.81615388,-0.32075776,92.49590024
2025-01-22 00:00:00-05:00,429.41119202,424.18848511,12658042084.26582527,-1550554.95095253,18.87998803,20.16824527,-6.41191942,NaN,NaN,8.90144315,441.75749969,446.52797520,430.92399902,415.32002285,0.58507171,0.76663914,255.39161902
2025-01-23 00:00:00-05:00,429.85378906,424.30632172,12676151106.50006104,7380508.45310974,19.03643888,20.66568841,-4.35563836,NaN,NaN,8.64062578,444.23999786,453.95723896,435.00399780,416.05075665,0.49878422,0.89714123,195.24876943
2025-01-24 00:00:00-05:00,430.30107056,424.41553238,12676358356.18267822,10429113.06714058,19.16668006,21.12008259,-2.88134453,NaN,NaN,8.40272377,444.31749725,455.54905147,438.90000000,422.25094853,0.56405719,-0.20952497,143.59889715